<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Incident_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load & Inspect Data

In [13]:

import chardet
with open("/content/drive/MyDrive/Project/Datasets/INCIDENTS.csv", "rb") as f:
    result = chardet.detect(f.read(1000_000))  # sample first 100k bytes

print(result)

{'encoding': 'Windows-1252', 'confidence': 0.7293068993579889, 'language': ''}

In [14]:

path = '/content/drive/MyDrive/Project/Datasets/INCIDENTS.csv'
df = pd.read_csv(path, encoding='Windows-1252')
df.head()

,IDINCIDENT,Type_incident,IDINCIDENT_Pere,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,DateH_incident,Lieu,Num_incident,Commentaire,Statut,Gravite,Motif_client,IDGARE,Statut_commercial,Statut_financier
0,201,CORDON_TIR,0.0,57,2020-01-02 23:18:00.000,87.0,2020-03-10 14:48:34.290,2020-01-02 21:00:00.000,Lyon,286,1 remorque LKW Walter avec conrdon de tir mal mis,3.0,3.0,CORDON_TIR,NaN,NaN,NaN
1,202,WAG. DIF,201.0,57,2020-01-02 23:20:00.000,57.0,2020-01-02 23:28:38.460,2020-01-02 22:00:00.000,Lyon,287,Wagon coupé suite à la mauvaise fermeture d'un...,NaN,NaN,NaN,NaN,NaN,NaN
2,203,WAG. DIF,0.0,57,2020-01-06 10:45:00.000,57.0,2020-01-13 07:12:50.120,2020-01-04 01:00:00.000,Tarvisio,288,wagon coupé suite bâche ouverte sur une remoru...,NaN,NaN,NaN,NaN,NaN,NaN
3,204,WAG. DIF,0.0,31,2020-01-07 15:12:01.000,57.0,2020-01-13 07:12:28.630,2020-01-06 20:00:00.000,Tarvisio,289,Wagon différé sur train 45668 du 06.01.2020 po...,NaN,NaN,NaN,NaN,NaN,NaN
4,205,UTI_MAL_CHARGEE,204.0,31,2020-01-07 15:18:00.000,57.0,2020-01-07 18:00:49.150,2020-01-06 20:00:00.000,Tarvisio,290,Wagon différé suite toit ouvert sur SR MARE 00...,NaN,NaN,UTI_MAL_CHARGEE,NaN,NaN,NaN

In [17]:
# Shape
df.shape

(5875, 17)

In [18]:
# Dtypes
df.dtypes

IDINCIDENT                  int64
Type_incident              object
IDINCIDENT_Pere           float64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                  object
DateH_incident             object
Lieu                       object
Num_incident                int64
Commentaire                object
Statut                    float64
Gravite                   float64
Motif_client               object
IDGARE                    float64
Statut_commercial         float64
Statut_financier          float64
dtype: object

In [19]:
# Missing values
df.isna().sum()

IDINCIDENT                   0
Type_incident                0
IDINCIDENT_Pere            279
IDUtilisateur_creation       0
DateH_creation               0
IDUtilisateur_maj           14
DateH_maj                   14
DateH_incident               0
Lieu                      1427
Num_incident                 0
Commentaire               1943
Statut                      25
Gravite                     25
Motif_client               109
IDGARE                    4535
Statut_commercial          872
Statut_financier           872
dtype: int64

In [20]:
# Missing values
df.isna().sum()

IDINCIDENT                   0
Type_incident                0
IDINCIDENT_Pere            279
IDUtilisateur_creation       0
DateH_creation               0
IDUtilisateur_maj           14
DateH_maj                   14
DateH_incident               0
Lieu                      1427
Num_incident                 0
Commentaire               1943
Statut                      25
Gravite                     25
Motif_client               109
IDGARE                    4535
Statut_commercial          872
Statut_financier           872
dtype: int64

In [21]:
# Columns
df.columns

Index(['IDINCIDENT', 'Type_incident', 'IDINCIDENT_Pere',
       'IDUtilisateur_creation', 'DateH_creation', 'IDUtilisateur_maj',
       'DateH_maj', 'DateH_incident', 'Lieu', 'Num_incident', 'Commentaire',
       'Statut', 'Gravite', 'Motif_client', 'IDGARE', 'Statut_commercial',
       'Statut_financier'],
      dtype='object')

In [22]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'IDINCIDENT': 5875,
 'Type_incident': 152,
 'IDINCIDENT_Pere': 290,
 'IDUtilisateur_creation': 20,
 'DateH_creation': 5853,
 'IDUtilisateur_maj': 22,
 'DateH_maj': 5856,
 'DateH_incident': 5469,
 'Lieu': 431,
 'Num_incident': 5875,
 'Commentaire': 3654,
 'Statut': 3,
 'Gravite': 6,
 'Motif_client': 148,
 'IDGARE': 83,
 'Statut_commercial': 5,
 'Statut_financier': 5}