<a href="https://colab.research.google.com/github/Donthula-Harika/freight-rail-delay-prediction/blob/data-analysis/notebooks/Incident_Concern_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Incident concern data analysis

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd

## Load dataset

In [ ]:

import chardet
with open("/content/drive/MyDrive/Project/Datasets/INCIDENT_CONCERN.csv", "rb") as f:
    result = chardet.detect(f.read(1000_000))  # sample first 100k bytes

print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [ ]:

path = '/content/drive/MyDrive/Project/Datasets/INCIDENT_CONCERN.csv'
df = pd.read_csv(path, encoding='ascii')
df.head()

/tmp/ipykernel_540/2131449936.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding='ascii')

,IDINCIDENT_CONCERNE,IDINCIDENT,IDTRAIN_UTI,IDTRAIN_WAGON,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,Unite,IDCOMMANDE_UTI,IDAGRES,IDFACTURE,IDTRAIN_LOT,IDWAGON,Annule_TrainLot,IDSOCIETE,IDFACTURE_FOUR
0,211,203,NaN,NaN,57,2020-01-06 10:45:57.680,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1,212,204,NaN,202074.0,31,2020-01-07 15:13:28.790,NaN,NaN,W,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2,214,205,71237.0,NaN,31,2020-01-07 15:18:36.470,NaN,NaN,U,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
3,215,206,NaN,NaN,83,2020-01-09 20:34:11.200,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
4,216,207,NaN,NaN,83,2020-01-09 20:44:54.270,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [ ]:
# Shape
df.shape

(59773, 17)

In [ ]:
# Dtypes
df.dtypes

IDINCIDENT_CONCERNE         int64
IDINCIDENT                  int64
IDTRAIN_UTI               float64
IDTRAIN_WAGON             float64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                 float64
Unite                      object
IDCOMMANDE_UTI            float64
IDAGRES                   float64
IDFACTURE                 float64
IDTRAIN_LOT               float64
IDWAGON                   float64
Annule_TrainLot             int64
IDSOCIETE                 float64
IDFACTURE_FOUR            float64
dtype: object

In [ ]:
# Missing values
df.isna().sum()

IDINCIDENT_CONCERNE           0
IDINCIDENT                    0
IDTRAIN_UTI               31009
IDTRAIN_WAGON             10589
IDUtilisateur_creation        0
DateH_creation                0
IDUtilisateur_maj         58353
DateH_maj                 59773
Unite                     59699
IDCOMMANDE_UTI            55195
IDAGRES                   59770
IDFACTURE                 59770
IDTRAIN_LOT                4740
IDWAGON                   59741
Annule_TrainLot               0
IDSOCIETE                 59747
IDFACTURE_FOUR            59749
dtype: int64

In [ ]:
# Columns
df.columns

Index(['IDINCIDENT_CONCERNE', 'IDINCIDENT', 'IDTRAIN_UTI', 'IDTRAIN_WAGON',
       'IDUtilisateur_creation', 'DateH_creation', 'IDUtilisateur_maj',
       'DateH_maj', 'Unite', 'IDCOMMANDE_UTI', 'IDAGRES', 'IDFACTURE',
       'IDTRAIN_LOT', 'IDWAGON', 'Annule_TrainLot', 'IDSOCIETE',
       'IDFACTURE_FOUR'],
      dtype='object')

In [ ]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'IDINCIDENT_CONCERNE': 59773,
 'IDINCIDENT': 5754,
 'IDTRAIN_UTI': 25300,
 'IDTRAIN_WAGON': 19010,
 'IDUtilisateur_creation': 19,
 'DateH_creation': 51286,
 'IDUtilisateur_maj': 1,
 'DateH_maj': 0,
 'Unite': 3,
 'IDCOMMANDE_UTI': 4141,
 'IDAGRES': 3,
 'IDFACTURE': 3,
 'IDTRAIN_LOT': 3467,
 'IDWAGON': 29,
 'Annule_TrainLot': 2,
 'IDSOCIETE': 8,
 'IDFACTURE_FOUR': 23}