<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Station_Gare_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Station Gare Analysis

In [1]:
import numpy as np
import pandas as pd

## Load and Inspect data

In [6]:
import chardet

with open("/content/drive/MyDrive/CVR College/Mini Project/data/STATION_GARE.csv", "rb") as f:
    result = chardet.detect(f.read(100_000))  # sample first 100k bytes

print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.7293868, 'language': ''}

In [8]:
path = '/content/drive/MyDrive/CVR College/Mini Project/data/STATION_GARE.csv'
df = pd.read_csv(path, encoding='ISO-8859-1')
df.head()

,Code_UIC,IDGARE,Code,Nom,NomComplet,Code_pays,IDGARE_Parent,Gare_Frontiere,Gare_Marchandises,Latitude,Longitude,Enr_actif,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,Type_gare,Top_Everysens_existe,Geojson
0,51.0,92940,02847-2,Clip( Poznan),Clip Intermodal Sp.zo.o( Poznan),PL,0,0,0,52.402759,17.095353,1,38,2020-01-24 09:02:01.000,38.0,2020-07-17 13:25:20.360,C,0,"{ ""coordinates"":[ [ [ 17.1176, 52.40234 ], [ 1..."
1,51.0,88733,2580,RZEPIN,RZEPIN,PL,0,0,0,0.000000,0.000000,1,1,2019-02-21 19:33:45.590,NaN,NaN,C,0,"{ ""coordinates"":[ [ [ 14.78159, 52.35107 ], [ ..."
2,71.0,92941,71901,Barcelona Can Tunis,Barcelona can Tunis,ES,0,0,0,41.346430,2.136822,1,31,2020-01-31 16:26:01.000,38.0,2020-07-17 13:11:22.420,C,0,"{ ""coordinates"":[ [ [ 2.147655, 41.344405 ], [..."
3,80.0,86282,1305,Kiel-Meimersdorf,Kiel-Meimersdorf,DE,0,0,0,54.285984,10.114312,1,1,2019-02-21 19:31:01.000,38.0,2020-07-17 12:52:07.700,I,0,"{ ""coordinates"":[ [ [ 10.130424, 54.298496 ], ..."
4,80.0,86455,580,Igel Grenze,Igel Grenze,DE,0,0,0,49.708270,6.547510,1,1,2019-02-21 19:31:01.000,38.0,2020-07-17 12:59:41.920,C,1,"{ ""coordinates"":[ 0, 0 ], ""type"":""Point"" }"

In [9]:
# Shape
df.shape

(7174, 19)

In [10]:
# Dtypes
df.dtypes

Code_UIC                  float64
IDGARE                      int64
Code                       object
Nom                        object
NomComplet                 object
Code_pays                  object
IDGARE_Parent               int64
Gare_Frontiere              int64
Gare_Marchandises           int64
Latitude                  float64
Longitude                 float64
Enr_actif                   int64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                  object
Type_gare                  object
Top_Everysens_existe        int64
Geojson                    object
dtype: object

In [12]:
# Missing values
df.isna().sum()

Code_UIC                  7038
IDGARE                       0
Code                         0
Nom                          0
NomComplet                   0
Code_pays                    0
IDGARE_Parent                0
Gare_Frontiere               0
Gare_Marchandises            0
Latitude                     0
Longitude                    0
Enr_actif                    0
IDUtilisateur_creation       0
DateH_creation               0
IDUtilisateur_maj         7065
DateH_maj                 7065
Type_gare                    0
Top_Everysens_existe         0
Geojson                   7006
dtype: int64

In [14]:
# Columns
df.columns

Index(['Code_UIC', 'IDGARE', 'Code', 'Nom', 'NomComplet', 'Code_pays',
       'IDGARE_Parent', 'Gare_Frontiere', 'Gare_Marchandises', 'Latitude',
       'Longitude', 'Enr_actif', 'IDUtilisateur_creation', 'DateH_creation',
       'IDUtilisateur_maj', 'DateH_maj', 'Type_gare', 'Top_Everysens_existe',
       'Geojson'],
      dtype='object')

In [27]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'Code_UIC': 8,
 'IDGARE': 7062,
 'Code': 6635,
 'Nom': 6998,
 'NomComplet': 6998,
 'Code_pays': 13,
 'IDGARE_Parent': 9,
 'Gare_Frontiere': 2,
 'Gare_Marchandises': 2,
 'Latitude': 53,
 'Longitude': 53,
 'Enr_actif': 2,
 'IDUtilisateur_creation': 7,
 'DateH_creation': 7042,
 'IDUtilisateur_maj': 6,
 'DateH_maj': 71,
 'Type_gare': 2,
 'Top_Everysens_existe': 2,
 'Geojson': 93}

In [28]:
df.Code_pays.value_counts() # Country codes - according to the research paper

Code_pays
DE    2081
FR    1343
PL     851
CH     589
AT     552
HR     479
HU     331
BE     291
NL     290
IT     288
LU      45
GR      32
ES       2
Name: count, dtype: int64