<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Terminal_stations_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Terminal Stations Analysis

In [1]:
import numpy as np
import pandas as pd

## Load & Inspect Data

In [2]:
path = '/content/drive/MyDrive/CVR College/Mini Project/data/TERMINAL.csv'
df = pd.read_csv(path)
df.head()

,IDTERMINAL,Nom_terminal,IDGARE_Desserte,Enr_actif,IDUtilisateur_creation,IDUtilisateur_maj,DateH_maj,DateH_creation,IDSOCIETE,Nom_court,IDGARE_Reseau,Maritime
0,1002,Lyon Terminal PEH,83760,1,1,31.0,2020-09-10 08:49:31.370,2018-12-10 11:58:00.000,703,Lyon,83760,0
1,1003,Anvers Combinant,82688,1,1,43.0,2019-05-21 17:17:35.450,2018-12-10 12:00:00.000,706,Anvers,82688,0
2,1004,Zeebrugge (Cobelfret Ro-Ro),82517,1,1,38.0,2021-02-22 12:40:56.600,2018-12-10 12:04:00.000,708,Zeeb,82517,1
3,1005,Bettembourg CT,80249,0,1,5.0,2019-02-21 13:59:40.090,2018-12-10 12:06:00.000,696,NaN,80249,0
4,1006,Champigneulles,84831,1,1,43.0,2019-05-21 17:17:59.650,2018-12-10 12:07:01.000,707,Champ,84831,0

In [8]:
df.shape

(19, 12)

In [3]:
df.columns

Index(['IDTERMINAL', 'Nom_terminal', 'IDGARE_Desserte', 'Enr_actif',
       'IDUtilisateur_creation', 'IDUtilisateur_maj', 'DateH_maj',
       'DateH_creation', 'IDSOCIETE', 'Nom_court', 'IDGARE_Reseau',
       'Maritime'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDTERMINAL              19 non-null     int64
 1   Nom_terminal            19 non-null     object
 2   IDGARE_Desserte         19 non-null     int64
 3   Enr_actif               19 non-null     int64
 4   IDUtilisateur_creation  19 non-null     int64
 5   IDUtilisateur_maj       13 non-null     float64
 6   DateH_maj               13 non-null     object
 7   DateH_creation          19 non-null     object
 8   IDSOCIETE               19 non-null     int64
 9   Nom_court               18 non-null     object
 10  IDGARE_Reseau           19 non-null     int64
 11  Maritime                19 non-null     int64
dtypes: float64(1), int64(7), object(4)
memory usage: 1.9+ KB

## Handle Missing Values

In [9]:
df.isna().sum()

IDTERMINAL                0
Nom_terminal              0
IDGARE_Desserte           0
Enr_actif                 0
IDUtilisateur_creation    0
IDUtilisateur_maj         6
DateH_maj                 6
DateH_creation            0
IDSOCIETE                 0
Nom_court                 1
IDGARE_Reseau             0
Maritime                  0
dtype: int64

## Identify Duplicates

In [10]:
df.duplicated().sum()

np.int64(0)