<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Wagon_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Wagon Data Analysis

In [1]:
import numpy as np
import pandas as pd

## Load Dataset

In [5]:
import chardet

path = '/content/drive/MyDrive/CVR College/Mini Project/data/TRAIN_WAGON.csv'
with open(path, 'rb') as f:
  result = chardet.detect(f.read(100_000))

print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [6]:
df = pd.read_csv(path, encoding='ascii')
df.head()

/tmp/ipykernel_460/346079939.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding='ascii')

,IDTRAIN_WAGON,IDWAGON,IDTRAIN_LOT,Num_Position,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,IDWAGON_MODELE,Top_wagon_maitre
0,138270,NaN,7138,0,31,2019-09-03 18:17:27.237,0.0,NaN,1,0
1,138271,NaN,7138,1,31,2019-09-03 18:17:27.243,0.0,NaN,2,0
2,138272,NaN,7138,2,31,2019-09-03 18:17:27.247,0.0,NaN,2,0
3,138273,NaN,7138,3,31,2019-09-03 18:17:27.253,0.0,NaN,2,0
4,138274,NaN,7138,4,31,2019-09-03 18:17:27.260,0.0,NaN,2,0

In [8]:
# Shape
df.shape

(226998, 10)

In [9]:
# Dtypes
df.dtypes

IDTRAIN_WAGON               int64
IDWAGON                   float64
IDTRAIN_LOT                 int64
Num_Position                int64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                  object
IDWAGON_MODELE              int64
Top_wagon_maitre            int64
dtype: object

In [10]:
# Missing values
df.isnull().sum()

IDTRAIN_WAGON                  0
IDWAGON                   157100
IDTRAIN_LOT                    0
Num_Position                   0
IDUtilisateur_creation         0
DateH_creation                 0
IDUtilisateur_maj          66537
DateH_maj                 226997
IDWAGON_MODELE                 0
Top_wagon_maitre               0
dtype: int64

In [11]:
# Columns
df.columns

Index(['IDTRAIN_WAGON', 'IDWAGON', 'IDTRAIN_LOT', 'Num_Position',
       'IDUtilisateur_creation', 'DateH_creation', 'IDUtilisateur_maj',
       'DateH_maj', 'IDWAGON_MODELE', 'Top_wagon_maitre'],
      dtype='object')