<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Lot_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Lot data analysis

In [1]:
import numpy as np
import pandas as pd

## Load and Inspect data

In [2]:
import chardet
path = '/content/drive/MyDrive/CVR College/Mini Project/data/TRAIN_LOT.csv'
with open(path, "rb") as f:
    result = chardet.detect(f.read(100_000))  # sample first 100k bytes

print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [3]:
# Load
df = pd.read_csv(path, encoding='ISO-8859-1')
df.head()

,IDTRAIN_LOT,IDTRAIN,Lot_num,DHR_Arrivee,DHT_Arrivee,Nom_lot,Commentaire,Distance,Poids_CO2,IDSOCIETE_Expediteur,...,Status,Longueur_totale,Voie_categorie,Voie_vitesse,Motif_suppression,DateH_suppression,IDSOCIETE_Client,DateH_info_fournisseur,Responsable_annulation,Top_reservation_interdite
0,255,255,1,NaN,NaN,NaN,NaN,99,0,688,...,1000,390.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,256,256,1,NaN,NaN,NaN,NaN,99,0,688,...,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,258,258,1,NaN,NaN,NaN,NaN,99,0,688,...,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,259,259,1,NaN,NaN,NaN,NaN,99,0,688,...,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,260,260,1,NaN,NaN,NaN,NaN,99,0,688,...,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [5]:
df.shape

(14692, 45)

In [6]:
df.columns

Index(['IDTRAIN_LOT', 'IDTRAIN', 'Lot_num', 'DHR_Arrivee', 'DHT_Arrivee',
       'Nom_lot', 'Commentaire', 'Distance', 'Poids_CO2',
       'IDSOCIETE_Expediteur', 'IDSOCIETE_Destinataire', 'IDJALON_Origine',
       'IDJALON_Destination', 'Surbooking', 'Objectif_CA', 'Objectif_TEU',
       'DHT_Depart', 'DHR_Depart', 'H_Depart_ecart', 'H_Arrivee_ecart',
       'IDUtilisateur_creation', 'DateH_creation', 'IDUtilisateur_maj',
       'DateH_maj', 'Ref_Expediteur', 'Ref_Destinataire', 'Train_Position',
       'Incoterm', 'Num_LDV', 'Objectif_T', 'Objectif_UTI', 'Nbre_TEU',
       'Capacite_TEU', 'Nbre_UTI', 'Poids_total', 'Status', 'Longueur_totale',
       'Voie_categorie', 'Voie_vitesse', 'Motif_suppression',
       'DateH_suppression', 'IDSOCIETE_Client', 'DateH_info_fournisseur',
       'Responsable_annulation', 'Top_reservation_interdite'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14692 entries, 0 to 14691
Data columns (total 45 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   IDTRAIN_LOT                14692 non-null  int64
 1   IDTRAIN                    14692 non-null  int64
 2   Lot_num                    14692 non-null  int64
 3   DHR_Arrivee                0 non-null      float64
 4   DHT_Arrivee                0 non-null      float64
 5   Nom_lot                    1800 non-null   object
 6   Commentaire                498 non-null    object
 7   Distance                   14692 non-null  int64
 8   Poids_CO2                  14692 non-null  int64
 9   IDSOCIETE_Expediteur       14692 non-null  int64
 10  IDSOCIETE_Destinataire     14692 non-null  int64
 11  IDJALON_Origine            14692 non-null  int64
 12  IDJALON_Destination        14692 non-null  int64
 13  Surbooking                 14692 non-null  int64
 14  Objectif_CA                14692 non-null  int64
 15  Objectif_TEU               14692 non-null  int64
 16  DHT_Depart                 0 non-null      float64
 17  DHR_Depart                 0 non-null      float64
 18  H_Depart_ecart             14692 non-null  int64
 19  H_Arrivee_ecart            14692 non-null  int64
 20  IDUtilisateur_creation     14692 non-null  int64
 21  DateH_creation             14692 non-null  object
 22  IDUtilisateur_maj          14692 non-null  int64
 23  DateH_maj                  10613 non-null  object
 24  Ref_Expediteur             1413 non-null   object
 25  Ref_Destinataire           1833 non-null   object
 26  Train_Position             14692 non-null  int64
 27  Incoterm                   14686 non-null  object
 28  Num_LDV                    4455 non-null   object
 29  Objectif_T                 14684 non-null  float64
 30  Objectif_UTI               14692 non-null  int64
 31  Nbre_TEU                   14649 non-null  float64
 32  Capacite_TEU               14649 non-null  float64
 33  Nbre_UTI                   14649 non-null  float64
 34  Poids_total                14649 non-null  float64
 35  Status                     14692 non-null  int64
 36  Longueur_totale            14625 non-null  float64
 37  Voie_categorie             0 non-null      float64
 38  Voie_vitesse               0 non-null      float64
 39  Motif_suppression          1672 non-null   object
 40  DateH_suppression          1258 non-null   object
 41  IDSOCIETE_Client           0 non-null      float64
 42  DateH_info_fournisseur     158 non-null    object
 43  Responsable_annulation     158 non-null    object
 44  Top_reservation_interdite  14692 non-null  int64
dtypes: float64(13), int64(20), object(12)
memory usage: 5.0+ MB

In [8]:
# Missing values
df.isna().sum()

IDTRAIN_LOT                      0
IDTRAIN                          0
Lot_num                          0
DHR_Arrivee                  14692
DHT_Arrivee                  14692
Nom_lot                      12892
Commentaire                  14194
Distance                         0
Poids_CO2                        0
IDSOCIETE_Expediteur             0
IDSOCIETE_Destinataire           0
IDJALON_Origine                  0
IDJALON_Destination              0
Surbooking                       0
Objectif_CA                      0
Objectif_TEU                     0
DHT_Depart                   14692
DHR_Depart                   14692
H_Depart_ecart                   0
H_Arrivee_ecart                  0
IDUtilisateur_creation           0
DateH_creation                   0
IDUtilisateur_maj                0
DateH_maj                     4079
Ref_Expediteur               13279
Ref_Destinataire             12859
Train_Position                   0
Incoterm                         6
Num_LDV                      10237
Objectif_T                       8
Objectif_UTI                     0
Nbre_TEU                        43
Capacite_TEU                    43
Nbre_UTI                        43
Poids_total                     43
Status                           0
Longueur_totale                 67
Voie_categorie               14692
Voie_vitesse                 14692
Motif_suppression            13020
DateH_suppression            13434
IDSOCIETE_Client             14692
DateH_info_fournisseur       14534
Responsable_annulation       14534
Top_reservation_interdite        0
dtype: int64