<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Jalgon_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Jalgon Data Analysis

In [1]:
import numpy as np
import pandas as pd

## Load Dataset

In [2]:
import chardet

path = '/content/drive/MyDrive/CVR College/Mini Project/data/TRAIN_JALON.csv'
with open(path, 'rb') as f:
    result = chardet.detect(f.read(100_000))

print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [5]:
df = pd.read_csv(path, encoding='latin-1')
df.head()

/tmp/ipykernel_390/849005887.py:1: DtypeWarning: Columns (19,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding='latin-1')

,IDTRAIN_JALON,Jalon_num,Lieu,DHR_Arrivee,DHT_Arrivee,DHT_Depart,DHR_Depart,IDTRAIN,IDGARE,Code_pays,...,IDUtilisateur_maj,DateH_maj,Commentaire,Distance_origine,H_Arrivee_ecart1,H_Arrivee_ecart2,H_Depart_ecart1,H_Depart_ecart2,DHO_Depart,DHO_Arrivee
0,3507,1,NaN,NaN,NaN,2019-03-04 01:50:00.000,NaN,255,80248,NaN,...,42.0,2021-01-18 16:15:44.890,NaN,NaN,0,0,0,0,NaN,NaN
1,3508,9999,NaN,NaN,2019-03-04 06:27:00.000,NaN,NaN,255,84831,NaN,...,0.0,NaN,NaN,NaN,0,0,0,0,NaN,NaN
2,3509,3,NaN,NaN,2019-03-04 05:30:00.000,2019-03-04 05:30:00.000,NaN,255,87910,NaN,...,0.0,NaN,NaN,NaN,0,0,0,0,NaN,NaN
3,3510,2,NaN,NaN,2019-03-04 04:50:00.000,2019-03-04 04:50:00.000,NaN,255,85792,NaN,...,0.0,NaN,NaN,NaN,0,0,0,0,NaN,NaN
4,3511,4,NaN,NaN,2019-03-04 05:40:00.000,2019-03-04 05:40:00.000,NaN,255,87942,NaN,...,0.0,NaN,NaN,NaN,0,0,0,0,NaN,NaN

In [6]:
# Shape
df.shape

(72531, 27)

In [7]:
# Columns
df.columns

Index(['IDTRAIN_JALON', 'Jalon_num', 'Lieu', 'DHR_Arrivee', 'DHT_Arrivee',
       'DHT_Depart', 'DHR_Depart', 'IDTRAIN', 'IDGARE', 'Code_pays',
       'Latitude', 'Longitude', 'Jalon_passage', 'H_Depart_ecart',
       'H_Arrivee_ecart', 'IDUtilisateur_creation', 'DateH_creation',
       'IDUtilisateur_maj', 'DateH_maj', 'Commentaire', 'Distance_origine',
       'H_Arrivee_ecart1', 'H_Arrivee_ecart2', 'H_Depart_ecart1',
       'H_Depart_ecart2', 'DHO_Depart', 'DHO_Arrivee'],
      dtype='object')

In [8]:
# Dtypes
df.dtypes

IDTRAIN_JALON               int64
Jalon_num                   int64
Lieu                      float64
DHR_Arrivee                object
DHT_Arrivee                object
DHT_Depart                 object
DHR_Depart                 object
IDTRAIN                     int64
IDGARE                      int64
Code_pays                 float64
Latitude                  float64
Longitude                 float64
Jalon_passage               int64
H_Depart_ecart              int64
H_Arrivee_ecart             int64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                  object
Commentaire                object
Distance_origine          float64
H_Arrivee_ecart1            int64
H_Arrivee_ecart2            int64
H_Depart_ecart1             int64
H_Depart_ecart2             int64
DHO_Depart                 object
DHO_Arrivee                object
dtype: object

In [9]:
# Missing values
df.isnull().sum()

IDTRAIN_JALON                 0
Jalon_num                     0
Lieu                      72531
DHR_Arrivee               50461
DHT_Arrivee               14220
DHT_Depart                14220
DHR_Depart                50525
IDTRAIN                       0
IDGARE                        0
Code_pays                 72531
Latitude                      0
Longitude                     0
Jalon_passage                 0
H_Depart_ecart                0
H_Arrivee_ecart               0
IDUtilisateur_creation        0
DateH_creation                0
IDUtilisateur_maj             5
DateH_maj                 50695
Commentaire               72342
Distance_origine          54226
H_Arrivee_ecart1              0
H_Arrivee_ecart2              0
H_Depart_ecart1               0
H_Depart_ecart2               0
DHO_Depart                50330
DHO_Arrivee               50328
dtype: int64