<a href="https://colab.research.google.com/github/Donthula-Harika/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Position_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Position Data Analysis

In [1]:
import numpy as np
import pandas as pd

## Load dataset

In [2]:
import chardet

path = '/content/drive/MyDrive/Project/Datasets/TRAIN_POSITION.csv'
with open(path, 'rb') as f:
    result = chardet.detect(f.read(100_000))

print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [3]:
df = pd.read_csv(path, encoding='ascii')
df.head()

   IDTRAIN_POSITION  IDTRAIN           DateH_position   Latitude  Longitude
0                 3    16515  2020-11-20 08:04:47.000  45.427223  10.978433
1                 4    16284  2020-11-20 09:15:37.000  47.587433  12.164879
2                 5    16452  2020-11-21 00:45:13.000  47.266020  11.402210
3                 6    16464  2020-11-23 05:10:50.000  45.638460  13.764245
4                 7    14748  2020-11-23 08:15:25.000  49.247090   6.163070

In [4]:
# Shape
df.shape

(25343, 5)

In [5]:
# Columns
df.columns

Index(['IDTRAIN_POSITION', 'IDTRAIN', 'DateH_position', 'Latitude',
       'Longitude'],
      dtype='object')

In [7]:
# Dtypes
df.dtypes

IDTRAIN_POSITION      int64
IDTRAIN               int64
DateH_position       object
Latitude            float64
Longitude           float64
dtype: object

In [8]:
# Missing values
df.isnull().sum()

IDTRAIN_POSITION    0
IDTRAIN             0
DateH_position      0
Latitude            0
Longitude           0
dtype: int64