<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Etape_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Etape Data Analysis

In [1]:
import numpy as np
import pandas as pd

## Load Dataset

In [5]:
import chardet

path = '/content/drive/MyDrive/CVR College/Mini Project/data/TRAIN_ETAPE.csv'
with open(path, 'rb') as f:
    result = chardet.detect(f.read(100_000))
print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [10]:
df = pd.read_csv(path, encoding='latin-1')
df.head()

/tmp/ipykernel_354/849005887.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding='latin-1')

,IDTRAIN_ETAPE,IDTRAIN_LOT,Type_etape,DH_Theorique,H_Thorique_ecart,DH_Reelle,DH_Theorique_fin,DH_Reelle_fin,Commentaire,IDUtilisateur_maj,DateH_maj,H_Theorique_ecart1,H_Theorique_ecart2
0,1794,255,PRELISTE CHARG,2019-03-02 10:00:00.000,0,NaN,2019-03-02 12:00:00.000,NaN,NaN,NaN,NaN,0,0
1,1795,255,LISTE CHARGEMENT,2019-03-02 16:00:00.000,0,NaN,2019-03-02 18:00:00.000,NaN,NaN,NaN,NaN,0,0
2,1796,255,CLOSING TRAIN,2019-03-04 00:01:00.000,0,NaN,2019-03-04 00:01:00.000,NaN,NaN,NaN,NaN,0,0
3,1797,255,CHARGEMENT,2019-03-03 22:00:00.000,0,NaN,2019-03-04 02:00:00.000,NaN,NaN,NaN,NaN,0,0
4,1798,255,VISITE,2019-03-04 03:00:00.000,0,NaN,2019-03-04 04:00:00.000,NaN,NaN,NaN,NaN,0,0

In [11]:
# Shape
df.shape

(147208, 13)

In [12]:
# Columns
df.columns

Index(['IDTRAIN_ETAPE', 'IDTRAIN_LOT', 'Type_etape', 'DH_Theorique',
       'H_Thorique_ecart', 'DH_Reelle', 'DH_Theorique_fin', 'DH_Reelle_fin',
       'Commentaire', 'IDUtilisateur_maj', 'DateH_maj', 'H_Theorique_ecart1',
       'H_Theorique_ecart2'],
      dtype='object')

In [13]:
# Dtypes
df.dtypes

IDTRAIN_ETAPE           int64
IDTRAIN_LOT             int64
Type_etape             object
DH_Theorique           object
H_Thorique_ecart        int64
DH_Reelle              object
DH_Theorique_fin       object
DH_Reelle_fin          object
Commentaire            object
IDUtilisateur_maj     float64
DateH_maj              object
H_Theorique_ecart1      int64
H_Theorique_ecart2      int64
dtype: object

In [14]:
# Missing values
df.isnull().sum()

IDTRAIN_ETAPE              0
IDTRAIN_LOT                0
Type_etape                 0
DH_Theorique              62
H_Thorique_ecart           0
DH_Reelle             102515
DH_Theorique_fin          62
DH_Reelle_fin         104565
Commentaire           147186
IDUtilisateur_maj     116705
DateH_maj             116799
H_Theorique_ecart1         0
H_Theorique_ecart2         0
dtype: int64