<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/data-analysis/notebooks/Train_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Analysis

In [3]:
import numpy as np
import pandas as pd

## Load and Inspect Dataset

In [4]:
import chardet

with open("/content/drive/MyDrive/CVR College/Mini Project/data/STATION_GARE.csv", "rb") as f:
    result = chardet.detect(f.read(100_000))  # sample first 100k bytes

print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.7293868, 'language': ''}

In [6]:
# Load
path = '/content/drive/MyDrive/CVR College/Mini Project/data/TRAIN.csv'
df = pd.read_csv(path, encoding='ISO-8859-1')
df.head()

,IDTRAIN,Train_num,IDRELATION,Sens,IDCONTACT_Responsable,Motif_suppression,IDTRAINREF_JOUR,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,IDATE,Commentaire,Poids_maxi,Longueur_maxi,DateH_suppression,IDSOCIETE_suppression,IDTRAIN_Parent,Generer_Orfeus
0,255,42951,2011,A,NaN,NaN,5047,5,2019-02-25 09:57:57.000,38,2021-02-01 16:24:38.510,7,NaN,1255,400,2019-09-10 14:58:09.480,NaN,NaN,0
1,256,42951,2011,A,NaN,Période de tests,5047,5,2019-02-25 09:57:56.577,0,2019-09-10 14:58:09.480,7,NaN,1255,400,2019-09-10 14:58:09.480,NaN,NaN,0
2,258,42951,2011,A,NaN,Période de tests,5047,5,2019-02-25 09:57:59.223,0,2019-09-10 14:58:09.480,7,NaN,1255,400,2019-09-10 14:58:09.480,NaN,NaN,0
3,259,42951,2011,A,NaN,Période de tests,5070,5,2019-02-25 09:57:58.617,0,2019-09-10 14:58:09.480,7,NaN,1255,400,2019-09-10 14:58:09.480,NaN,NaN,0
4,260,42951,2011,A,NaN,Période de tests,5070,5,2019-02-25 09:57:59.363,0,2019-09-10 14:58:09.480,7,NaN,1255,400,2019-09-10 14:58:09.480,NaN,NaN,0

In [7]:
# Shape
df.shape

(14215, 19)

In [8]:
# Columns
df.columns

Index(['IDTRAIN', 'Train_num', 'IDRELATION', 'Sens', 'IDCONTACT_Responsable',
       'Motif_suppression', 'IDTRAINREF_JOUR', 'IDUtilisateur_creation',
       'DateH_creation', 'IDUtilisateur_maj', 'DateH_maj', 'IDATE',
       'Commentaire', 'Poids_maxi', 'Longueur_maxi', 'DateH_suppression',
       'IDSOCIETE_suppression', 'IDTRAIN_Parent', 'Generer_Orfeus'],
      dtype='object')

In [9]:
# Dtypes
df.dtypes

IDTRAIN                     int64
Train_num                  object
IDRELATION                  int64
Sens                       object
IDCONTACT_Responsable     float64
Motif_suppression          object
IDTRAINREF_JOUR             int64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj           int64
DateH_maj                  object
IDATE                       int64
Commentaire                object
Poids_maxi                  int64
Longueur_maxi               int64
DateH_suppression          object
IDSOCIETE_suppression     float64
IDTRAIN_Parent            float64
Generer_Orfeus              int64
dtype: object

In [10]:
# Missing values
df.isnull().sum()

IDTRAIN                       0
Train_num                     0
IDRELATION                    0
Sens                          0
IDCONTACT_Responsable      2380
Motif_suppression          8970
IDTRAINREF_JOUR               0
IDUtilisateur_creation        0
DateH_creation                0
IDUtilisateur_maj             0
DateH_maj                  3711
IDATE                         0
Commentaire                9777
Poids_maxi                    0
Longueur_maxi                 0
DateH_suppression          8921
IDSOCIETE_suppression     13895
IDTRAIN_Parent            14076
Generer_Orfeus                0
dtype: int64