<a href="https://colab.research.google.com/github/RishithaSrija/freight-rail-delay-prediction/blob/data-analysis/notebooks/Wagon_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Wagon Tables

**WAGON** — Master record for each physical wagon with technical specs like tare weight, brake type, and circulation status.

In [1]:
import numpy as np
import pandas as pd

##Load and Inspect data

In [5]:
import chardet
with open("/content/drive/MyDrive/Mini_project(3-2)/WAGON.csv","rb") as f:
  res=chardet.detect(f.read(100_000))
  print(res)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [14]:
path = '/content/drive/MyDrive/Mini_project(3-2)/WAGON.csv'
df = pd.read_csv(path, encoding='ascii')
df.head(20)

,IDWAGON_MODELE,Modele_wagon,Caracteristiques,Type_wagon,Lettres_categories,Enr_actif,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,...,Nb_Positions_maxi,IDNHM_vide,IDNHM_Charge,Tare,Capacite_Pe,Capacite_Pf,Capacite_Pg,Chargement_mode,CentreCout,Regroupement_analytique_wagon
0,9,40',PORTE_CONTENEURS,SIMPLE,SGMMNSS,1,19,2019-04-03 12:04:00.000,38,2020-11-25 09:59:58.860,...,2,6379,NaN,16200,0,0,0,NaN,40WAG-CT,WAGONS CT 40'
1,2,60',PORTE_CONTENEURS,SIMPLE,Sgnss,1,1,2018-12-05 13:51:20.000,38,2020-11-25 10:00:17.050,...,3,6379,NaN,19800,0,0,0,NaN,40WAG-CT,WAGONS CT 60'
2,5,90',PORTE_CONTENEURS,DOUBLE,Sggmrss,1,1,2018-12-05 13:51:31.000,38,2020-10-05 10:09:03.410,...,4,6379,NaN,27200,0,0,0,NaN,40WAG-CT,WAGONS CT 90'
3,13,Convent. L: 19900 cm,CONVENTIONNEL CARGO,WAGON PLAT,RNSS1,1,31,2021-02-01 19:26:02.000,31,2021-02-03 16:34:33.210,...,1,6394,NaN,23900,0,0,0,V,40ROSTOCK,CONVENTIONNEL 1990
4,14,Convent. L: 26240 cm,CONVENTIONNEL CARGO,WAGON PLAT,RBS LONG,1,31,2021-02-01 19:26:03.000,31,2021-02-03 17:37:10.390,...,1,6394,NaN,30100,0,0,0,V,40ROSTOCK,CONVENTIONNEL 1990
5,12,"Conventionnel19,90 m",CONVENTIONNEL CARGO,WAGON PLAT,RENSSS 1,0,31,2021-02-01 19:26:03.000,31,2021-02-03 16:31:36.340,...,1,6394,NaN,24380,0,0,0,V,40ROSTOCK,CONVENTIONNEL 1990
6,10,Multifret,PORTE_CONTENEURS,DOUBLE,SFFGGMRRS(S),1,18,2019-04-23 14:20:32.000,38,2020-10-05 10:09:10.330,...,4,6379,NaN,35000,0,0,0,NaN,40WAG-CT,WAGONS CT 90'
7,11,T3000e C30,PORTE_CONTENEURS_POC,DOUBLE,Sdggmrss,1,1,2018-12-05 13:51:19.000,316,2021-02-22 16:25:36.320,...,4,6379,NaN,35000,1,0,0,NaN,40WAG-SR,WAGONS SR
8,6,T3000e NIK,PORTE_CONTENEURS_POC,DOUBLE,Sdggmrss,1,1,2018-12-05 13:51:35.000,31,2021-02-04 19:23:54.080,...,4,6379,NaN,35000,1,0,0,NaN,40WAG-SR,WAGONS SR
9,1,T3000e NIK C30,PORTE_CONTENEURS_POC,DOUBLE,Sdggmrss,1,1,2018-12-05 13:51:18.000,42,2021-02-22 17:15:38.360,...,4,6379,NaN,35000,1,0,0,NaN,40WAG-SR,WAGONS SR
10,3,TWIN 1,PORTE_CONTENEURS_POC,DOUBLE,Sdggmrs(s)-D,1,1,2018-12-05 13:51:29.000,38,2020-10-05 10:09:40.730,...,4,6379,NaN,35000,0,0,0,NaN,40WAG-SR,WAGONS SR
11,4,TWIN 2,PORTE_CONTENEURS_POC,DOUBLE,Sdggmrs(s)-D,1,1,2018-12-05 13:51:28.000,38,2020-10-05 10:09:50.670,...,4,6379,NaN,35000,0,0,0,NaN,40WAG-SR,WAGONS SR
12,7,UIC 1,POCHE,DOUBLE,Sdmrs,1,1,2018-12-05 13:51:39.000,38,2020-10-05 10:10:03.000,...,2,6379,NaN,41700,0,0,0,NaN,40WAG-MOD,WAGONS MOD
13,8,UIC 2,POCHE,DOUBLE,Sdmrs,1,1,2018-12-05 13:51:40.000,38,2020-10-05 10:10:09.420,...,2,6379,NaN,40700,0,0,0,NaN,40WAG-MOD,WAGONS MOD

In [9]:
#shape
df.shape

(14, 43)

In [10]:
#data types
df.dtypes

IDWAGON_MODELE                     int64
Modele_wagon                      object
Caracteristiques                  object
Type_wagon                        object
Lettres_categories                object
Enr_actif                          int64
IDUtilisateur_creation             int64
DateH_creation                    object
IDUtilisateur_maj                  int64
DateH_maj                         object
Frein_regime                      object
Vitesse_maxi                       int64
Longueur_HT                        int64
Longueur_HTp                     float64
Nb_Plateaux                        int64
Longueur_utile                     int64
Hauteur_chargt                     int64
Charge_utile                       int64
Charge_TEU                       float64
Charge_essieu                      int64
Roue_diam                        float64
Courbure_rayon                     int64
Plancher_hauteur_rail              int64
Poche_longueur                     int64
Nb_essieux                         int64
Charge_AS                          int64
Charge_ASS                         int64
Charge_BS                          int64
Charge_BSS                         int64
Charge_CS                          int64
Charge_CSS                         int64
Charge_DS                          int64
Charge_DSS                         int64
Nb_Positions_maxi                  int64
IDNHM_vide                         int64
IDNHM_Charge                     float64
Tare                               int64
Capacite_Pe                        int64
Capacite_Pf                        int64
Capacite_Pg                        int64
Chargement_mode                   object
CentreCout                        object
Regroupement_analytique_wagon     object
dtype: object

In [11]:
#Null values
df.isna().sum()

IDWAGON_MODELE                    0
Modele_wagon                      0
Caracteristiques                  0
Type_wagon                        0
Lettres_categories                0
Enr_actif                         0
IDUtilisateur_creation            0
DateH_creation                    0
IDUtilisateur_maj                 0
DateH_maj                         0
Frein_regime                      0
Vitesse_maxi                      0
Longueur_HT                       0
Longueur_HTp                      0
Nb_Plateaux                       0
Longueur_utile                    0
Hauteur_chargt                    0
Charge_utile                      0
Charge_TEU                        0
Charge_essieu                     0
Roue_diam                         0
Courbure_rayon                    0
Plancher_hauteur_rail             0
Poche_longueur                    0
Nb_essieux                        0
Charge_AS                         0
Charge_ASS                        0
Charge_BS                         0
Charge_BSS                        0
Charge_CS                         0
Charge_CSS                        0
Charge_DS                         0
Charge_DSS                        0
Nb_Positions_maxi                 0
IDNHM_vide                        0
IDNHM_Charge                     14
Tare                              0
Capacite_Pe                       0
Capacite_Pf                       0
Capacite_Pg                       0
Chargement_mode                  11
CentreCout                        0
Regroupement_analytique_wagon     0
dtype: int64

In [12]:
#columns
df.columns

Index(['IDWAGON_MODELE', 'Modele_wagon', 'Caracteristiques', 'Type_wagon',
       'Lettres_categories', 'Enr_actif', 'IDUtilisateur_creation',
       'DateH_creation', 'IDUtilisateur_maj', 'DateH_maj', 'Frein_regime',
       'Vitesse_maxi', 'Longueur_HT', 'Longueur_HTp', 'Nb_Plateaux',
       'Longueur_utile', 'Hauteur_chargt', 'Charge_utile', 'Charge_TEU',
       'Charge_essieu', 'Roue_diam', 'Courbure_rayon', 'Plancher_hauteur_rail',
       'Poche_longueur', 'Nb_essieux', 'Charge_AS', 'Charge_ASS', 'Charge_BS',
       'Charge_BSS', 'Charge_CS', 'Charge_CSS', 'Charge_DS', 'Charge_DSS',
       'Nb_Positions_maxi', 'IDNHM_vide', 'IDNHM_Charge', 'Tare',
       'Capacite_Pe', 'Capacite_Pf', 'Capacite_Pg', 'Chargement_mode',
       'CentreCout', 'Regroupement_analytique_wagon'],
      dtype='object')

In [13]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'IDWAGON_MODELE': 14,
 'Modele_wagon': 14,
 'Caracteristiques': 4,
 'Type_wagon': 3,
 'Lettres_categories': 10,
 'Enr_actif': 2,
 'IDUtilisateur_creation': 4,
 'DateH_creation': 13,
 'IDUtilisateur_maj': 4,
 'DateH_maj': 14,
 'Frein_regime': 1,
 'Vitesse_maxi': 2,
 'Longueur_HT': 10,
 'Longueur_HTp': 4,
 'Nb_Plateaux': 2,
 'Longueur_utile': 7,
 'Hauteur_chargt': 4,
 'Charge_utile': 8,
 'Charge_TEU': 4,
 'Charge_essieu': 2,
 'Roue_diam': 3,
 'Courbure_rayon': 4,
 'Plancher_hauteur_rail': 4,
 'Poche_longueur': 2,
 'Nb_essieux': 3,
 'Charge_AS': 7,
 'Charge_ASS': 6,
 'Charge_BS': 7,
 'Charge_BSS': 6,
 'Charge_CS': 9,
 'Charge_CSS': 7,
 'Charge_DS': 7,
 'Charge_DSS': 7,
 'Nb_Positions_maxi': 4,
 'IDNHM_vide': 2,
 'IDNHM_Charge': 0,
 'Tare': 9,
 'Capacite_Pe': 2,
 'Capacite_Pf': 1,
 'Capacite_Pg': 1,
 'Chargement_mode': 1,
 'CentreCout': 4,
 'Regroupement_analytique_wagon': 6}

In [16]:
df.Caracteristiques.value_counts()

Caracteristiques
PORTE_CONTENEURS_POC    5
PORTE_CONTENEURS        4
CONVENTIONNEL CARGO     3
POCHE                   2
Name: count, dtype: int64