<a href="https://colab.research.google.com/github/RishithaSrija/freight-rail-delay-prediction/blob/data-analysis/notebooks/Wagon_Capacity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Wagon Capacity Data Analysis

**WAGON_CAPACITY** — Defines the loading capacity specifications (C, N, P ratings) for each wagon model.

In [1]:
import numpy as np
import pandas as pd

##Load and Inspect data

In [3]:
import chardet
with open("/content/drive/MyDrive/Mini_project(3-2)/WAGON_CAPACITE.csv","rb") as f:
  res=chardet.detect(f.read(100_000))
  print(res)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [4]:
path = '/content/drive/MyDrive/Mini_project(3-2)/WAGON_CAPACITE.csv'
df = pd.read_csv(path, encoding='ascii')
df.head(20)

,IDWAGON_CAPACITE,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,IDWAGON_MODELE,Code_pays,Capacite_C,Capacite_N,Capacite_P
0,3,5,2019-04-19 16:01:25.487,NaN,NaN,9,CH,NaN,NaN,6.0
1,4,39,2019-05-03 12:18:44.623,NaN,NaN,6,CH,NaN,NaN,6.0
2,5,39,2019-05-03 12:20:27.203,NaN,NaN,1,CH,NaN,NaN,6.0
3,6,39,2019-05-08 15:33:23.643,NaN,NaN,9,NaN,2.0,NaN,NaN
4,7,39,2019-05-08 15:37:01.187,NaN,NaN,1,BE,NaN,NaN,5.0
5,8,39,2019-05-08 15:37:01.207,NaN,NaN,1,DE,NaN,NaN,6.0
6,9,39,2019-05-08 15:37:01.227,NaN,NaN,1,SE,NaN,NaN,6.0
7,10,39,2019-05-13 15:19:23.843,NaN,NaN,4,CH,NaN,NaN,6.0
8,11,39,2019-05-13 15:19:23.883,NaN,NaN,4,DE,NaN,NaN,6.0
9,12,39,2019-05-13 15:19:23.923,NaN,NaN,4,NL,NaN,NaN,6.0
10,13,39,2019-05-13 15:19:23.953,NaN,NaN,4,BE,NaN,NaN,6.0
11,14,39,2019-05-13 15:19:23.993,NaN,NaN,4,GB,NaN,NaN,6.0
12,15,39,2019-05-13 15:19:24.033,NaN,NaN,4,DK,NaN,NaN,6.0
13,16,39,2019-05-13 15:19:24.063,NaN,NaN,4,NO,NaN,NaN,6.0
14,17,39,2019-05-13 15:19:24.093,NaN,NaN,4,IT,NaN,NaN,0.0
15,18,39,2019-05-13 15:19:24.123,NaN,NaN,4,PL,NaN,NaN,0.0
16,19,39,2019-05-13 15:19:24.153,NaN,NaN,4,AT,NaN,NaN,0.0
17,20,39,2019-05-13 15:19:24.183,NaN,NaN,4,LU,NaN,NaN,0.0
18,21,39,2019-05-13 15:19:24.213,NaN,NaN,4,FR,NaN,NaN,0.0
19,22,37,2019-06-04 14:59:01.003,NaN,NaN,5,NaN,0.0,NaN,0.0

In [5]:
#shape
df.shape

(29, 10)

In [6]:
#data types
df.dtypes

IDWAGON_CAPACITE            int64
IDUtilisateur_creation      int64
DateH_creation             object
IDUtilisateur_maj         float64
DateH_maj                 float64
IDWAGON_MODELE              int64
Code_pays                  object
Capacite_C                float64
Capacite_N                float64
Capacite_P                float64
dtype: object

In [7]:
#Null values
df.isna().sum()

IDWAGON_CAPACITE           0
IDUtilisateur_creation     0
DateH_creation             0
IDUtilisateur_maj         29
DateH_maj                 29
IDWAGON_MODELE             0
Code_pays                  7
Capacite_C                23
Capacite_N                27
Capacite_P                 2
dtype: int64

In [8]:
#columns
df.columns

Index(['IDWAGON_CAPACITE', 'IDUtilisateur_creation', 'DateH_creation',
       'IDUtilisateur_maj', 'DateH_maj', 'IDWAGON_MODELE', 'Code_pays',
       'Capacite_C', 'Capacite_N', 'Capacite_P'],
      dtype='object')

In [9]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'IDWAGON_CAPACITE': 29,
 'IDUtilisateur_creation': 4,
 'DateH_creation': 24,
 'IDUtilisateur_maj': 0,
 'DateH_maj': 0,
 'IDWAGON_MODELE': 7,
 'Code_pays': 13,
 'Capacite_C': 2,
 'Capacite_N': 1,
 'Capacite_P': 3}

In [10]:
df.Code_pays.value_counts()

Code_pays
CH    5
BE    3
DE    3
SE    2
NL    1
GB    1
DK    1
NO    1
IT    1
PL    1
AT    1
LU    1
FR    1
Name: count, dtype: int64