<a href="https://colab.research.google.com/github/RishithaSrija/freight-rail-delay-prediction/blob/data-analysis/notebooks/Wagon_Position_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Wagon_Position
**WAGON_POSITION** —
Tracks the last-known GPS position of an individual wagon at a given timestamp.

In [1]:
import numpy as np
import pandas as pd

##Load and Inspect data

In [3]:
import chardet
with open("/content/drive/MyDrive/Mini_project(3-2)/WAGON_POSITION.csv","rb") as f:
  res=chardet.detect(f.read(100_000))
  print(res)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [4]:
path = '/content/drive/MyDrive/Mini_project(3-2)/WAGON_POSITION.csv'
df = pd.read_csv(path, encoding='ascii')
df.head(20)

,IDWAGON_POSITION,IDWAGON,DateH_position,Latitude,Longitude,Application_GPS,Qualifiant,Etat_position
0,1,37,2020-11-20 15:11:13.000,51.371796,4.282741,NaN,NaN,NaN
1,2,247,2020-11-20 14:05:59.000,48.094210,11.809816,NaN,NaN,NaN
2,3,247,2020-11-20 14:11:13.000,48.118225,11.699616,NaN,NaN,NaN
3,4,247,2020-11-20 14:16:35.000,48.122265,11.595469,NaN,NaN,NaN
4,5,247,2020-11-20 14:21:48.000,48.136540,11.526796,NaN,NaN,NaN
5,6,247,2020-11-20 14:27:01.000,48.144707,11.507050,NaN,NaN,NaN
6,7,247,2020-11-20 14:28:24.000,48.145180,11.504237,NaN,NaN,NaN
7,8,247,2020-11-20 14:39:11.000,48.145153,11.503295,NaN,NaN,NaN
8,9,247,2020-11-20 14:49:22.000,48.145153,11.503373,NaN,NaN,NaN
9,10,247,2020-11-20 14:58:24.000,48.145008,11.503424,NaN,NaN,NaN
10,11,247,2020-11-20 15:18:37.000,48.145200,11.500172,NaN,NaN,NaN
11,12,247,2020-11-20 15:23:55.000,48.148487,11.465438,NaN,NaN,NaN
12,13,247,2020-11-20 15:24:27.000,48.148445,11.465364,NaN,NaN,NaN
13,14,247,2020-11-20 15:27:42.000,48.150257,11.462438,NaN,NaN,NaN
14,15,247,2020-11-20 15:33:01.000,48.191486,11.381064,NaN,NaN,NaN
15,16,247,2020-11-20 15:44:56.000,48.218380,11.122450,NaN,NaN,NaN
16,17,247,2020-11-20 15:50:08.000,48.250126,11.016069,NaN,NaN,NaN
17,18,247,2020-11-20 15:55:21.000,48.290913,10.961870,NaN,NaN,NaN
18,19,247,2020-11-20 16:00:31.000,48.302162,10.959209,NaN,NaN,NaN
19,20,266,2020-11-20 15:15:30.000,51.371070,4.282829,NaN,NaN,NaN

In [5]:
#shape
df.shape

(1048574, 8)

In [6]:
#data types
df.dtypes

IDWAGON_POSITION      int64
IDWAGON               int64
DateH_position       object
Latitude            float64
Longitude           float64
Application_GPS     float64
Qualifiant          float64
Etat_position       float64
dtype: object

In [7]:
#columns
df.columns

Index(['IDWAGON_POSITION', 'IDWAGON', 'DateH_position', 'Latitude',
       'Longitude', 'Application_GPS', 'Qualifiant', 'Etat_position'],
      dtype='object')

In [8]:
# Unique values in each column
col_unique_counts = {}
for col in df.columns:
    col_unique_counts[col] = df[col].nunique()

col_unique_counts

{'IDWAGON_POSITION': 1048574,
 'IDWAGON': 323,
 'DateH_position': 522908,
 'Latitude': 336590,
 'Longitude': 486488,
 'Application_GPS': 0,
 'Qualifiant': 0,
 'Etat_position': 0}