<a href="https://colab.research.google.com/github/akashgardas/freight-rail-delay-prediction/blob/model-building/notebooks/model_building/Linear_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Build Linear Regression Model

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
path = '/content/drive/MyDrive/CVR College/Mini Project/data/Finalized data/preprocessed_data.csv'

## Load Preprocessed Data

In [ ]:
df = pd.read_csv(path)
df.head()

   arrival_delay_time  teu_count  ...  weight_per_length  weight_per_wagon
0                   0        0.0  ...              990.0           18900.0
1                   0        0.0  ...              990.0           18900.0
2                   0        0.0  ...              990.0           18900.0
3                   0        0.0  ...              990.0           18900.0
4                   0        0.0  ...              990.0           18900.0

[5 rows x 7 columns]

In [ ]:
df.isna().sum()

arrival_delay_time      0
teu_count               0
train_length            0
total_distance_trip     0
departure_delay_time    0
weight_per_length       0
weight_per_wagon        0
dtype: int64

In [ ]:
df.columns

Index(['arrival_delay_time', 'teu_count', 'train_length',
       'total_distance_trip', 'departure_delay_time', 'weight_per_length',
       'weight_per_wagon'],
      dtype='object')

## Feature separation

In [ ]:
X = df.drop('arrival_delay_time', axis=1)
y = df['arrival_delay_time']

## Split into train test split

In [ ]:
# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Build Model

In [ ]:
model =  LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

## Evaluate Model

In [ ]:
# evaluate model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 842.8652596260723
R-squared: 0.2264368030772702

## Export model

In [ ]:
# Export model
import joblib

# Export the model to a file
joblib.dump(model, 'my_model.joblib')

# --- To load it back later ---
# loaded_model = joblib.load('my_model.joblib')

['my_model.joblib']